blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug Report
    url: https://xenanetworks.com/support/bug-report/
    about: Create a report to help us improve XOA Utility.
  - name: âœ¨ Feature Request
    url: https://xenanetworks.com/support/feature-request/
    about: Suggest an idea for XOA Utility.
  - name: ğŸ§ Question
    url: https://xenanetworks.com/support/question/
    about: Ask us a question about XOA Utility.
  - name: ğŸ“ Check XOA Utility Documentation
    url: https://docs.xenanetworks.com/projects/xoa-utility
    about: The answer you are looking for may be in here.
  